#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f lfsr4.vcd

#run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace lfsr4.sv --exe lfsr4_tb.cpp

# build c++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vlfsr4.mk Vlfsr4

#run executable simulation file
obj_dir/Vlfsr4
